
---
title: "CodeBook"
output: html_document
---

##Codes for output file "TidyData.txt"
Number in square brackets denotes the column number

 [1] "Activity_label"                      
  FACTOR:  6 Levels  equating to Activity

  WALKING
  WALKING_UPSTAIRS
  WALKING_DOWNSTAIRS
  SITTING
  STANDING
  LAYING

[2] "Subject"                             
   FACTOR:  30 Levels equating to Subject Number
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12
  13
  14
  15
  16
  17
  18
  19
  20
  21
  22
  23
  24
  25
  26
  27
  28
  29
  30
 
 [3] "Data"
 FACTOR: 2 Levels equating to whether the data was derived from the test     or train data sets
 TEST
 TRAIN
 
[4] "tBodyAcc.mean...X"                   
  Mean time domain signalof Body Acceleration on the X axial direction
  
[5] "tBodyAcc.mean...Y"                   
   Mean time domain signal of Body Acceleration on the Y axial direction
 
[6] "tBodyAcc.mean...Z"                   
   Mean time domain signal of Body Acceleration on the Z axial direction
  
[7] "tGravityAcc.mean...X"                
  Mean time domain signal of Gravity Acceleration on the X axial         direction

[8] "tGravityAcc.mean...Y"                
  Mean time domain signal of Gravity Acceleration on the Y axial direction

[9] "tGravityAcc.mean...Z"                
  Mean time domain signal of Gravity Acceleration on the Z axial direction

[10] "tBodyAccJerk.mean...X"               
  Mean time domain signal of Body Acceleration Jerk on the X axial direction

[12] "tBodyAccJerk.mean...Z"
  Mean time domain signal of Body Acceleration Jerk on the Z axial direction

[13] "tBodyGyro.mean...X"   
  Mean time domain signal of Body Gyroscope on the X axial direction

[14] "tBodyGyro.mean...Y"
  Mean time domain signal of Body Gyroscope on the Y axial direction

[15] "tBodyGyro.mean...Z"
  Mean time domain signal of Body Gyroscope on the Z axial direction

[16] "tBodyGyroJerk.mean...X" 
  Mean time domain signal of Body Gyroscope Jerk on the X axial direction

[17] "tBodyGyroJerk.mean...Y"              
  Mean time domain signal of Body Gyroscope Jerk on the Y axial direction

[18] "tBodyGyroJerk.mean...Z"              
  Mean time domain signal of Body Gyroscope Jerk on the Z axial direction

[19] "tBodyAccMag.mean.."                  
  Mean magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Body Acceleration

[20] "tGravityAccMag.mean.."   
  Mean magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Gravity Acceleration

[21] "tBodyAccJerkMag.mean.."  
  Mean magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Body Acceleration Jerk

[22] "tBodyGyroMag.mean.."
  Mean magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Body Gyroscope

[23] "tBodyGyroJerkMag.mean.." 
  Mean magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Body Gyroscope Jerk

[24] "fBodyAcc.mean...X" 
  Mean frequency domain signal of Body Acceleration on the X axial direction
                       
[25] "fBodyAcc.mean...Y"  
  Mean frequency domain signal of Body Acceleration on the Y axial direction
          
[26] "fBodyAcc.mean...Z" 
 Mean frequency domain signal of Body Acceleration on the Z axial direction
          
[27] "fBodyAcc.meanFreq...X"  
  Mean frequency domain signal of Body Acceleration frequency on the X axial direction

[28] "fBodyAcc.meanFreq...Y"               
  Mean frequency domain signal of Body Acceleration frequency on the Y axial direction

[29] "fBodyAcc.meanFreq...Z" 
 Mean frequency domain signal of Body Acceleration frequency on the Z axial direction

[30] "fBodyAccJerk.mean...X"  
 Mean frequency domain signal of Body Acceleration Jerk on the X axial direction

[31] "fBodyAccJerk.mean...Y"               
Mean frequency domain signal of Body Acceleration Jerk on the Y axial direction

[32] "fBodyAccJerk.mean...Z"      
Mean frequency domain signal of Body Acceleration Jerk on the Z axial direction
 
[33] "fBodyAccJerk.meanFreq...X"           
Mean frequency domain signal of Body Acceleration Jerk frequency on the X axial direction

[34] "fBodyAccJerk.meanFreq...Y"           
Mean frequency domain signal of Body Acceleration Jerk frequency on the Y axial direction

[35] "fBodyAccJerk.meanFreq...Z"           
Mean frequency domain signal of Body Acceleration Jerk frequency on the Z axial direction

[36] "fBodyGyro.mean...X"           
  Mean frequency domain signal of Body Gyroscope on the X axial direction

[37] "fBodyGyro.mean...Y"                  
Mean frequency domain signal of Body Gyroscope on the Y axial direction

[38] "fBodyGyro.mean...Z"                  
Mean frequency domain signal of Body Gyroscope on the Z axial direction

[39] "fBodyGyro.meanFreq...X"              
Mean frequency domain signal of Body Gyroscope frequency on the X axial direction

[40] "fBodyGyro.meanFreq...Y"              
Mean frequency domain signal of Body Gyroscope frequency on the Y axial direction

[41] "fBodyGyro.meanFreq...Z"              
Mean frequency domain signal of Body Gyroscope frequency on the Z axial direction

[42] "fBodyAccMag.mean.."                  
Mean magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Acceleration

[43] "fBodyAccMag.meanFreq.."              
Mean magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Acceleration frequency

[44] "fBodyBodyAccJerkMag.mean.."          
Mean magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Acceleration Jerk

[45] "fBodyBodyAccJerkMag.meanFreq.."      
Mean magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Acceleration Jerk frequency

[46] "fBodyBodyGyroMag.mean.."             
  Mean magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Gyroscope

[47] "fBodyBodyGyroMag.meanFreq.."    
Mean  magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Gyroscope frequency
     
[48] "fBodyBodyGyroJerkMag.mean.."         
Mean magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Gyroscope Jerk

[49] "fBodyBodyGyroJerkMag.meanFreq.."     
magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Gyroscope Jerk Frequency

[50] "angle.tBodyAccMean.gravity."         
Angle between vectors Mean time domain signal of Body Acceleration and Gravity acceleration 

[51] "angle.tBodyAccJerkMean..gravityMean."
Angle between vectors Mean time domain signal of Body Acceleration Jerk and Gravity 

[52] "angle.tBodyGyroMean.gravityMean."    
Angle between vectors Mean time domain signal of Body Gyroscope and  Gravity

[53] "angle.tBodyGyroJerkMean.gravityMean."
Angle between vectors Mean time domain signal of Body Gyroscope Jerk and  Mean Gravity

[54] "angle.X.gravityMean."                
Angle between vectors Mean Gravity on the X axial direction

[55] "angle.Y.gravityMean."                
Angle between vectors Mean Gravity on the Y axial direction

[56] "angle.Z.gravityMean."                
Angle between vectors Mean Gravity on the Z axial direction

[57] "tBodyAcc.std...X"                    
Standard deviation of time domain signalof Body Acceleration on the X axial direction

[58] "tBodyAcc.std...Y"                    
Standard deviation of time domain signalof Body Acceleration on the Y axial direction

[59] "tBodyAcc.std...Z"
Standard deviation of time domain signalof Body Acceleration on the Z axial direction

[60] "tGravityAcc.std...X"                 
  Standard deviation of time domain signal of Gravity Acceleration on the X axial direction

[61] "tGravityAcc.std...Y"                 
  Standard deviation of time domain signal of Gravity Acceleration on the Y axial direction

[62] "tGravityAcc.std...Z"                 
  Standard deviation of time domain signal of Gravity Acceleration on the X axial direction

[63] "tBodyAccJerk.std...X"                
Standard deviation of time domain signal of Body Acceleration Jerk on the X axial direction

[64] "tBodyAccJerk.std...Y"                
Standard deviation domain signal of Body Acceleration Jerk on the Y axial direction

[65] "tBodyAccJerk.std...Z"                
Standard deviation domain signal of Body Acceleration Jerk on the Z axial direction

[66] "tBodyGyro.std...X"                   
Standard deviation of time domain signal of Body Gyroscope on the X axial direction

[67] "tBodyGyro.std...Y"                   
Standard deviation of time domain signal of Body Gyroscope on the Y axial direction

[68] "tBodyGyro.std...Z"                   
Standard deviation of time domain signal of Body Gyroscope on the Z axial direction

[69] "tBodyGyroJerk.std...X"               
Standard deviation time domain signal of Body Gyroscope Jerk on the X axial direction

[70] "tBodyGyroJerk.std...Y"               
Standard deviation time domain signal of Body Gyroscope Jerk on the Y axial direction

[71] "tBodyGyroJerk.std...Z"               
Standard deviation time domain signal of Body Gyroscope Jerk on the Z axial direction

[72] "tBodyAccMag.std.."                   
 Standard deviation of magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Body Acceleration

[73] "tGravityAccMag.std.." 
Standard deviation of magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Gravity Acceleration               

[74] "tBodyAccJerkMag.std.." 
Standard deviation of  magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Body Acceleration Jerk    

[75] "tBodyGyroMag.std.."    
Standard deviation of magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Body Gyroscope            

[76] "tBodyGyroJerkMag.std.."    
Standard deviation of   magnitude (calculated as Euclidean norm) X, Y, Z axial direction for Mean time domain signal of Body Gyroscope Jerk  

[77] "fBodyAcc.std...X"
Standard deviation of  frequency domain signal of Body Acceleration on the X axial direction

[78] "fBodyAcc.std...Y"
Standard deviation of frequency domain signal of Body Acceleration on the Y axial direction               

[79] "fBodyAcc.std...Z"
Standard deviation of frequency domain signal of Body Acceleration on the Z axial direction
                   
[80] "fBodyAccJerk.std...X"                
Standard deviation frequency domain signal of Body Acceleration Jerk on the X axial direction

[81] "fBodyAccJerk.std...Y"                
Standard deviation frequency domain signal of Body Acceleration Jerk on the Y axial direction

[82] "fBodyAccJerk.std...Z"    
Standard deviation frequency domain signal of Body Acceleration Jerk on the Z axial direction

[83] "fBodyGyro.std...X"
Standard deviation of frequency domain signal of Body Gyroscope on the X axial direction
                 
[84] "fBodyGyro.std...Y"    
Standard deviation of frequency domain signal of Body Gyroscope on the Y axial direction
           
[85] "fBodyGyro.std...Z"         
Standard deviation of frequency domain signal of Body Gyroscope on the Z axial direction
          
[86] "fBodyAccMag.std.."        
Standard deviation of magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Acceleration
         
[87] "fBodyBodyAccJerkMag.std.."        
 Standard deviation of magnitude (derived from Fast Fourier Transform) X, Y, Z axial direction for Mean frequency domain signal of Body Acceleration Jerk

##Codes for output file "Summary.txt"

[1] "Activity_label"
FACTOR: 6 Levels equating to Activity

WALKING 
WALKING_UPSTAIRS 
WALKING_DOWNSTAIRS 
SITTING 
STANDING 
LAYING

[2] "Subject"
FACTOR: 30 Levels equating to Subject Number 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

Column names [3-86] are identical to column names [4-87] in TidyData.txt and they represent the same variables 
as above but with the variables meaned for each subject and each Activity level.

Column numbers are as above but -1 from the number in brackets
